services:
  gateway:
    build:
      context: ./gateway/service
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./gateway/service:/var/www
      - ./gateway/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - ./gateway/service/.env
    depends_on:
      - tasks
      - auth
    networks:
      - msxphp

  gateway-nginx:
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - ./gateway/service:/var/www
      - ./gateway/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888:80
    depends_on:
      - gateway
    networks:
      - msxphp

  auth-nginx:
    image: nginx:alpine
    working_dir: /var/www
    expose:
      - 80
    volumes:
      - ./auth/service:/var/www
      - ./auth/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
    networks:
      - msxphp

  tasks-nginx:
    image: nginx:alpine
    working_dir: /var/www
    expose:
      - 80
    volumes:
      - ./tasks/service:/var/www
      - ./tasks/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tasks
    networks:
      - msxphp

  tasks:
    build:
      context: ./tasks/service
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./tasks/service:/var/www
      - ./tasks/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - ./tasks/service/.env
    depends_on:
      - db-tasks
    networks:
      - msxphp

  auth:
    build:
      context: ./auth/service
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./auth/service:/var/www
      - ./auth/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - ./auth/service/.env
    depends_on:
      - db-auth
    networks:
      - msxphp

  db-tasks:
    image: mysql:8.0
    env_file:
      - ./db-tasks/.env
    volumes:
      - db-tasks-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - msxphp

  db-auth:
    image: mysql:8.0
    env_file:
      - ./db-auth/.env
    volumes:
      - db-auth-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - msxphp

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - msxphp

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - msxphp

  adminer:
    image: adminer
    env_file:
      - ./adminer/.env
    ports:
      - 8181:8080
    networks:
      - msxphp

volumes:
  db-tasks-data:
  db-auth-data:

networks:
  msxphp:
    driver: bridge
